// src/screens/marketplace/constants.js

export const SHOP_CATEGORIES = [
  { id: 'all', label: 'All', icon: 'th-large', color: '#FF2020' },
  { id: 'grocery', label: 'Grocery', icon: 'shopping-basket', color: '#22C55E' },
  { id: 'pharmacy', label: 'Pharmacy', icon: 'plus-square', color: '#14B8A6' },
  { id: 'electronics', label: 'Electronics', icon: 'mobile', color: '#3B82F6' },
  { id: 'clothing', label: 'Clothing', icon: 'tags', color: '#A855F7' },
  { id: 'hardware', label: 'Hardware', icon: 'wrench', color: '#FF8C00' },
  { id: 'food', label: 'Food', icon: 'cutlery', color: '#F97316' },
];

export const DUMMY_SHOPS = [
  {
    id: 's1',
    name: 'Mama Njeri Groceries',
    category: 'grocery',
    color: '#22C55E',
    icon: 'shopping-basket',
    distance: '0.4 km',
    deliveryRadiusKm: 3,
    isOpen: true,
    rating: 4.7,
    totalRatings: 128,
    description: 'Fresh produce, cereals, and household essentials. Delivery within Westlands.',
    phone: '+254712345678',
    whatsapp: '+254712345678',
    hours: 'Mon–Sat 7am–8pm',
    address: 'Westlands, Nairobi',
    isVerified: true,
    coordinates: { latitude: -1.2680, longitude: 36.8120 },
    tags: ['Fresh Produce', 'Cereals', 'Household'],
    productCount: 48,
    minOrder: 200,
    deliveryFee: 50,
  },
  {
    id: 's2',
    name: 'TechHub Electronics',
    category: 'electronics',
    color: '#3B82F6',
    icon: 'mobile',
    distance: '1.1 km',
    deliveryRadiusKm: 5,
    isOpen: true,
    rating: 4.5,
    totalRatings: 84,
    description: 'Phone accessories, cables, chargers, and repair parts.',
    phone: '+254723456789',
    whatsapp: '+254723456789',
    hours: 'Mon–Sun 9am–7pm',
    address: 'CBD, Nairobi',
    isVerified: true,
    coordinates: { latitude: -1.2840, longitude: 36.8200 },
    tags: ['Phones', 'Accessories', 'Repair'],
    productCount: 112,
    minOrder: 0,
    deliveryFee: 100,
  },
  {
    id: 's3',
    name: 'QuickMeds Pharmacy',
    category: 'pharmacy',
    color: '#14B8A6',
    icon: 'plus-square',
    distance: '0.7 km',
    deliveryRadiusKm: 2,
    isOpen: true,
    rating: 4.9,
    totalRatings: 210,
    description: 'OTC medicines, supplements, and personal care products.',
    phone: '+254734567890',
    whatsapp: '+254734567890',
    hours: 'Mon–Sun 8am–10pm',
    address: 'Parklands, Nairobi',
    isVerified: true,
    coordinates: { latitude: -1.2600, longitude: 36.8180 },
    tags: ['OTC', 'Supplements', 'Personal Care'],
    productCount: 230,
    minOrder: 100,
    deliveryFee: 80,
  },
  {
    id: 's4',
    name: 'Jua Kali Hardware',
    category: 'hardware',
    color: '#FF8C00',
    icon: 'wrench',
    distance: '1.8 km',
    deliveryRadiusKm: 4,
    isOpen: false,
    rating: 4.3,
    totalRatings: 56,
    description: 'Building materials, tools, plumbing and electrical supplies.',
    phone: '+254745678901',
    whatsapp: '+254745678901',
    hours: 'Mon–Sat 7am–6pm',
    address: 'Industrial Area, Nairobi',
    isVerified: false,
    coordinates: { latitude: -1.3020, longitude: 36.8380 },
    tags: ['Tools', 'Plumbing', 'Electrical'],
    productCount: 340,
    minOrder: 500,
    deliveryFee: 200,
  },
  {
    id: 's5',
    name: 'Zawadi Boutique',
    category: 'clothing',
    color: '#A855F7',
    icon: 'tags',
    distance: '2.2 km',
    deliveryRadiusKm: 6,
    isOpen: true,
    rating: 4.6,
    totalRatings: 93,
    description: 'Ladies fashion, handbags and accessories. Quality mitumba and new arrivals.',
    phone: '+254756789012',
    whatsapp: '+254756789012',
    hours: 'Mon–Sun 9am–8pm',
    address: 'Ngara, Nairobi',
    isVerified: false,
    coordinates: { latitude: -1.2780, longitude: 36.8280 },
    tags: ['Ladies', 'Bags', 'Mitumba'],
    productCount: 67,
    minOrder: 0,
    deliveryFee: 150,
  },
  {
    id: 's6',
    name: 'Kenchic Fast Foods',
    category: 'food',
    color: '#F97316',
    icon: 'cutlery',
    distance: '0.9 km',
    deliveryRadiusKm: 3,
    isOpen: true,
    rating: 4.4,
    totalRatings: 176,
    description: 'Fried chicken, burgers, fries and soft drinks. Fast delivery.',
    phone: '+254767890123',
    whatsapp: '+254767890123',
    hours: 'Mon–Sun 10am–11pm',
    address: 'Westlands, Nairobi',
    isVerified: true,
    coordinates: { latitude: -1.2700, longitude: 36.8090 },
    tags: ['Chicken', 'Burgers', 'Fast Food'],
    productCount: 28,
    minOrder: 300,
    deliveryFee: 60,
  },
];

export const DUMMY_PRODUCTS = {
  s1: [
    { id: 'p1', shopId: 's1', name: 'Unga wa Ngano 2kg', price: 185, category: 'Cereals', inStock: true, unit: 'per bag' },
    { id: 'p2', shopId: 's1', name: 'Fresh Tomatoes', price: 60, category: 'Produce', inStock: true, unit: 'per kg' },
    { id: 'p3', shopId: 's1', name: 'Sukuma Wiki', price: 30, category: 'Produce', inStock: true, unit: 'per bunch' },
    { id: 'p4', shopId: 's1', name: 'Cooking Oil 1L', price: 280, category: 'Cooking', inStock: true, unit: 'per bottle' },
    { id: 'p5', shopId: 's1', name: 'Sugar 1kg', price: 145, category: 'Cereals', inStock: false, unit: 'per kg' },
    { id: 'p6', shopId: 's1', name: 'Fresh Avocados', price: 20, category: 'Produce', inStock: true, unit: 'each' },
    { id: 'p7', shopId: 's1', name: 'Onions 1kg', price: 80, category: 'Produce', inStock: true, unit: 'per kg' },
    { id: 'p8', shopId: 's1', name: 'Maize Flour 2kg', price: 160, category: 'Cereals', inStock: true, unit: 'per bag' },
  ],
  s2: [
    { id: 'p9', shopId: 's2', name: 'USB-C Cable 1m', price: 350, category: 'Cables', inStock: true, unit: 'each' },
    { id: 'p10', shopId: 's2', name: 'Screen Protector (Universal)', price: 150, category: 'Accessories', inStock: true, unit: 'each' },
    { id: 'p11', shopId: 's2', name: 'Power Bank 10000mAh', price: 1800, category: 'Charging', inStock: true, unit: 'each' },
    { id: 'p12', shopId: 's2', name: 'Phone Case (Samsung A15)', price: 250, category: 'Accessories', inStock: false, unit: 'each' },
    { id: 'p13', shopId: 's2', name: 'Earphones (Wired)', price: 450, category: 'Audio', inStock: true, unit: 'each' },
    { id: 'p14', shopId: 's2', name: 'Fast Charger 33W', price: 850, category: 'Charging', inStock: true, unit: 'each' },
  ],
  s3: [
    { id: 'p15', shopId: 's3', name: 'Panadol Extra (12 tabs)', price: 65, category: 'OTC', inStock: true, unit: 'per pack' },
    { id: 'p16', shopId: 's3', name: 'Vitamin C 500mg (30 tabs)', price: 320, category: 'Supplements', inStock: true, unit: 'per bottle' },
    { id: 'p17', shopId: 's3', name: 'Hand Sanitizer 500ml', price: 280, category: 'Personal Care', inStock: true, unit: 'per bottle' },
    { id: 'p18', shopId: 's3', name: 'Bandages Assorted', price: 120, category: 'First Aid', inStock: true, unit: 'per box' },
    { id: 'p19', shopId: 's3', name: 'Strepsils (24 tabs)', price: 180, category: 'OTC', inStock: false, unit: 'per pack' },
  ],
  s4: [
    { id: 'p20', shopId: 's4', name: 'Hammer (500g)', price: 650, category: 'Tools', inStock: true, unit: 'each' },
    { id: 'p21', shopId: 's4', name: 'PVC Pipe 1/2 inch (3m)', price: 280, category: 'Plumbing', inStock: true, unit: 'per piece' },
    { id: 'p22', shopId: 's4', name: 'Wire Nails 1kg', price: 150, category: 'Fasteners', inStock: true, unit: 'per kg' },
    { id: 'p23', shopId: 's4', name: 'Paint Brush Set', price: 420, category: 'Painting', inStock: true, unit: 'per set' },
  ],
  s5: [
    { id: 'p24', shopId: 's5', name: 'Ladies Dress (Ankara)', price: 1200, category: 'Dresses', inStock: true, unit: 'each' },
    { id: 'p25', shopId: 's5', name: 'Handbag (Leather)', price: 2500, category: 'Bags', inStock: true, unit: 'each' },
    { id: 'p26', shopId: 's5', name: 'Sandals (Size 37–40)', price: 800, category: 'Footwear', inStock: false, unit: 'per pair' },
    { id: 'p27', shopId: 's5', name: 'Blouse (Cotton)', price: 650, category: 'Tops', inStock: true, unit: 'each' },
  ],
  s6: [
    { id: 'p28', shopId: 's6', name: 'Chicken Quarter', price: 280, category: 'Chicken', inStock: true, unit: 'each' },
    { id: 'p29', shopId: 's6', name: 'Chips Regular', price: 150, category: 'Sides', inStock: true, unit: 'each' },
    { id: 'p30', shopId: 's6', name: 'Burger Meal', price: 450, category: 'Burgers', inStock: true, unit: 'each' },
    { id: 'p31', shopId: 's6', name: 'Soft Drink 500ml', price: 80, category: 'Drinks', inStock: true, unit: 'each' },
    { id: 'p32', shopId: 's6', name: 'Full Chicken', price: 950, category: 'Chicken', inStock: true, unit: 'each' },
  ],
};